name: Deploy to main machine

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker Image (production mode)
        run: |
          docker buildx build --build-arg NODE_ENV=production -t ${{ secrets.DOCKER_HUB_USERNAME }}/tychicus-dashboard:prod --platform linux/amd64 .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/tychicus-dashboard:prod

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy
        run: |
          DOCKER_IMAGE="${{ secrets.DOCKER_HUB_USERNAME }}/tychicus-dashboard:prod"
          sshpass -p ${{ secrets.DEV_MACHINE_SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no -t ${{ secrets.DEV_MACHINE_SSH_USER }}@${{ secrets.DEV_MACHINE_SSH_HOST }} -p ${{ secrets.DEV_MACHINE_SSH_PORT }} "
            docker rm -f tychicus-dashboard-prod || true
            docker rmi ${DOCKER_IMAGE} || true
            docker pull ${DOCKER_IMAGE}
            docker run -d -p 8180:80 --name tychicus-dashboard-prod --network hephai-bridge --restart unless-stopped ${DOCKER_IMAGE}
          "
